[workspace]
members = [ "advanced-traits","merkle-tree/"]

[profile.release]
panic = "unwind"

[workspace.package]
authors = ["TheLowLevelers <thelowlevelers@gmail.com>"]
edition = "2021"
repository = "https://github.com/lowlevelers/data-structure.git"
license = "GPL-3.0-only"
